-- HEX_CINDEC.dbo.S2iD definição

-- Drop table

-- DROP TABLE HEX_CINDEC.dbo.S2iD;

CREATE TABLE HEX_CINDEC.dbo.S2iD (
	UF varchar(55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Município varchar(55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Registro date NULL,
	Protocolo varchar(55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COBRADE varchar(181) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	Status varchar(55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	População int NULL,
	DH_Mortos int NULL,
	DH_Feridos int NULL,
	DH_Enfermos int NULL,
	DH_Desabrigados int NULL,
	DH_Desalojados int NULL,
	DH_Desaparecidos int NULL,
	[DH_Outros Afetados] int NULL,
	[DM_Unidades Habitacionais Danificadas] int NULL,
	[DM_Unidades Habitacionais Destruídas] int NULL,
	[DM_Unidades Habitacionais Valor] decimal(18,2) NULL,
	[DM_Instalações públicas de saúde Danificadas] int NULL,
	[DM_Instalações públicas de saúde Destruídas] int NULL,
	[DM_Instalações públicas de saúde Valor] decimal(18,2) NULL,
	[DM_Instalações públicas de ensino Danificadas] int NULL,
	[DM_Instalações públicas de ensino Destruídas] int NULL,
	[DM_Instalações públicas de ensino Valor] decimal(18,2) NULL,
	[DM_Instalações públicas prestadoras de outros serviços Danificadas] int NULL,
	[DM_Instalações públicas prestadoras de outros serviços Destruídas] int NULL,
	[DM_Instalações públicas prestadoras de outros serviços Valor] decimal(18,2) NULL,
	[DM_Instalações públicas de uso comunitário Danificadas] int NULL,
	[DM_Instalações públicas de uso comunitário Destruídas] int NULL,
	[DM_Instalações públicas de uso comunitário Valor] decimal(18,2) NULL,
	[DM_Obras de infraestrutura pública Danificadas] int NULL,
	[DM_Obras de infraestrutura pública Destruídas] int NULL,
	[DM_Obras de infraestrutura pública Valor] decimal(18,2) NULL,
	[DA_Poluição ou contaminação da água] decimal(18,2) NULL,
	[DA_Poluição ou contaminação do ar] decimal(18,2) NULL,
	[DA_Poluição ou contaminação do solo] decimal(18,2) NULL,
	[DA_Diminuição ou exaurimento hídrico] varchar(55) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DA_Incêndios em parques, APA's ou APP's] decimal(18,2) NULL,
	[PEPL_Assistência médica, saúde pública e atendimento de emergências médicas (R$)] int NULL,
	[PEPL_Abastecimento de água potável (R$)] int NULL,
	[PEPL_Esgoto de águas pluviais e sistema de esgotos sanitários (R$)] int NULL,
	[PEPL_Sistema de limpeza urbana e de recolhimento e destinação do lixo (R$)] int NULL,
	[PEPL_Sistema de desinfestação/desinfecção do habitat/controle de pragas e vetores (R$)] int NULL,
	[PEPL_Geração e distribuição de energia elétrica (R$)] int NULL,
	[PEPL_Telecomunicações (R$)] int NULL,
	[PEPL_Transportes locais, regionais e de longo curso (R$)] decimal(18,2) NULL,
	[PEPL_Distribuição de combustíveis, especialmente os de uso doméstico (R$)] int NULL,
	[PEPL_Segurança pública (R$)] int NULL,
	[PEPL_Ensino (R$)] int NULL,
	[PEPR_Agricultura (R$)] decimal(18,2) NULL,
	[PEPR_Pecuária (R$)] decimal(18,2) NULL,
	[PEPR_Indústria (R$)] int NULL,
	[PEPR_Comércio (R$)] int NULL,
	[PEPR_Serviços (R$)] int NULL
);