[program:ranking-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/artisan queue:work redis-ranking --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/ranking-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=180
startsecs=0
