<?php

declare(strict_types=1);

namespace App\Modules\Rat\DTOs;

/**
 * DTO para dados de envolvidos em uma ocorrência RAT.
 */
readonly class RatEnvolvidoDTO
{
    public function __construct(
        // ID do registro (para updates)
        public ?int $id = null,
        public ?int $seq = null,

        // Dados Gerais (g_)
        public ?string $gTipoPessoa = null,
        public ?string $gLesaoGrau = null,
        public ?string $gLesaoGrauSelecionado = null,
        public ?string $gAtendimentoVitimaRepassada = null,
        public ?bool   $gEnvolvidoPresenca = null,
        public ?string $gEnvolvidoTipo = null,
        public ?string $gEnvolvidoOrgao = null,
        public ?string $gEnvolvidoUf = null,
        public ?string $gEnvolvidoMatricula = null,
        public ?bool   $gEnvolvidoServico = null,

        // Dados Pessoais (p_)
        public ?string $pTipo = null,
        public ?string $pTipoSelecionado = null,
        public ?string $pNumero = null,
        public ?string $pOrgaoExpedidor = null,
        public ?string $pUf = null,
        public ?int    $pIdadeAparente = null,
        public ?string $pNomeCompleto = null,
        public ?string $pNomeFantasia = null,
        public ?string $pDataNascimento = null,
        public ?string $pCpf = null,
        public ?string $pNomeMae = null,
        public ?string $pNomePai = null,
        public ?string $pOcupacaoAtual = null,
        public ?string $pEscolaridade = null,
        public ?string $pCorRaca = null,
        public ?string $pCorRacaCod = null,
        public ?string $pSexo = null,
        public ?string $pSexoSelecionado = null,
        public ?string $pEstadoCivil = null,
        public ?string $pOrientacaoSexual = null,
        public ?string $pIdentidadeGenero = null,
        public ?string $pNomeSocial = null,
        public ?string $pNacionalidade = null,
        public ?string $pPaisOrigem = null,
        public ?string $pNaturalidadeUf = null,
        public ?bool   $pTurista = null,
        public ?bool   $pSituacaoRua = null,

        // Endereço (p_end_)
        public ?string $pEndCep = null,
        public ?string $pEndPais = null,
        public ?string $pEndEstadoUf = null,
        public ?string $pEndMunicipio = null,
        public ?string $pEndBairro = null,
        public ?string $pEndLogradouro = null,
        public ?string $pEndNumero = null,
        public ?string $pEndComplemento = null,
        public ?string $pEndKm = null,
        public ?string $pEndIbge = null,

        // Contato (p_)
        public ?string $pTelefoneResidencial = null,
        public ?string $pTelefoneComercial = null,
        public ?string $pEmail = null,
        public ?string $pMotivoAusenciaContato = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id:                            $data['id']                             ?? null,
            seq:                           $data['seq']                            ?? null,
            gTipoPessoa:                   $data['g_tipo_pessoa']                  ?? $data['tipo_envolvimento'] ?? null,
            gLesaoGrau:                    $data['g_lesao_grau']                   ?? null,
            gLesaoGrauSelecionado:         $data['g_lesao_grau_selecionado']       ?? null,
            gAtendimentoVitimaRepassada:   $data['g_atendimento_vitima_repassada']  ?? null,
            gEnvolvidoPresenca:            isset($data['g_envolvido_presenca'])    ? (bool) $data['g_envolvido_presenca'] : null,
            gEnvolvidoTipo:                $data['g_envolvido_tipo']               ?? null,
            gEnvolvidoOrgao:               $data['g_envolvido_orgao']              ?? null,
            gEnvolvidoUf:                  $data['g_envolvido_uf']                 ?? null,
            gEnvolvidoMatricula:           $data['g_envolvido_matricula']          ?? null,
            gEnvolvidoServico:             isset($data['g_envolvido_servico'])     ? (bool) $data['g_envolvido_servico'] : null,
            pTipo:                         $data['p_tipo']                         ?? null,
            pTipoSelecionado:              $data['p_tipo_selecionado']             ?? null,
            pNumero:                       $data['p_numero']                       ?? $data['rg'] ?? null,
            pOrgaoExpedidor:               $data['p_orgao_expedidor']              ?? null,
            pUf:                           $data['p_uf']                           ?? null,
            pIdadeAparente:                isset($data['p_idade_aparente']) && $data['p_idade_aparente'] !== ''
                                               ? (int) $data['p_idade_aparente'] : null,
            pNomeCompleto:                 $data['p_nome_completo']                ?? $data['nome'] ?? null,
            pNomeFantasia:                 $data['p_nome_fantasia']                ?? null,
            pDataNascimento:               $data['p_data_nascimento']              ?? $data['data_nascimento'] ?? null,
            pCpf:                          $data['p_cpf']                          ?? $data['cpf'] ?? null,
            pNomeMae:                      $data['p_nome_mae']                     ?? null,
            pNomePai:                      $data['p_nome_pai']                     ?? null,
            pOcupacaoAtual:                $data['p_ocupacao_atual']               ?? null,
            pEscolaridade:                 $data['p_escolaridade']                 ?? null,
            pCorRaca:                      $data['p_cor_raca']                     ?? null,
            pCorRacaCod:                   $data['p_cor_raca_cod']                 ?? null,
            pSexo:                         $data['p_sexo']                         ?? $data['sexo'] ?? null,
            pSexoSelecionado:              $data['p_sexo_selecionado']             ?? null,
            pEstadoCivil:                  $data['p_estado_civil']                 ?? null,
            pOrientacaoSexual:             $data['p_orientacao_sexual']            ?? null,
            pIdentidadeGenero:             $data['p_identidade_genero']            ?? null,
            pNomeSocial:                   $data['p_nome_social']                  ?? null,
            pNacionalidade:                $data['p_nacionalidade']                ?? null,
            pPaisOrigem:                   $data['p_pais_origem']                  ?? null,
            pNaturalidadeUf:               $data['p_naturalidade_uf']              ?? null,
            pTurista:                      isset($data['p_turista'])               ? (bool) $data['p_turista'] : null,
            pSituacaoRua:                  isset($data['p_situacao_rua'])          ? (bool) $data['p_situacao_rua'] : null,
            pEndCep:                       $data['p_end_cep']                      ?? $data['cep'] ?? null,
            pEndPais:                      $data['p_end_pais']                     ?? null,
            pEndEstadoUf:                  $data['p_end_estado_uf']                ?? $data['uf'] ?? null,
            pEndMunicipio:                 $data['p_end_municipio']                ?? $data['municipio'] ?? null,
            pEndBairro:                    $data['p_end_bairro']                   ?? $data['bairro'] ?? null,
            pEndLogradouro:                $data['p_end_logradouro']               ?? $data['endereco'] ?? null,
            pEndNumero:                    $data['p_end_numero']                   ?? null,
            pEndComplemento:               $data['p_end_complemento']              ?? null,
            pEndKm:                        $data['p_end_km']                       ?? null,
            pEndIbge:                      $data['p_end_ibge']                     ?? null,
            pTelefoneResidencial:         $data['p_telefone_residencial']         ?? $data['telefone'] ?? null,
            pTelefoneComercial:           $data['p_telefone_comercial']           ?? null,
            pEmail:                        $data['p_email']                        ?? null,
            pMotivoAusenciaContato:       $data['p_motivo_ausencia_contato']      ?? null,
        );
    }

    public function toArray(): array
    {
        return array_filter([
            'seq'                            => $this->seq,
            'g_tipo_pessoa'                  => $this->gTipoPessoa,
            'g_lesao_grau'                   => $this->gLesaoGrau,
            'g_lesao_grau_selecionado'       => $this->gLesaoGrauSelecionado,
            'g_atendimento_vitima_repassada' => $this->gAtendimentoVitimaRepassada,
            'g_envolvido_presenca'          => $this->gEnvolvidoPresenca,
            'g_envolvido_tipo'              => $this->gEnvolvidoTipo,
            'g_envolvido_orgao'             => $this->gEnvolvidoOrgao,
            'g_envolvido_uf'                => $this->gEnvolvidoUf    ? mb_substr($this->gEnvolvidoUf, 0, 2)    : null,
            'g_envolvido_matricula'         => $this->gEnvolvidoMatricula,
            'g_envolvido_servico'           => $this->gEnvolvidoServico,
            'p_tipo'                        => $this->pTipo,
            'p_tipo_selecionado'            => $this->pTipoSelecionado,
            'p_numero'                      => $this->pNumero,
            'p_orgao_expedidor'             => $this->pOrgaoExpedidor,
            'p_uf'                          => $this->pUf,
            'p_idade_aparente'              => $this->pIdadeAparente,
            'p_nome_completo'               => $this->pNomeCompleto,
            'p_nome_fantasia'               => $this->pNomeFantasia,
            'p_data_nascimento'             => $this->pDataNascimento,
            'p_cpf'                         => $this->pCpf,
            'p_nome_mae'                    => $this->pNomeMae,
            'p_nome_pai'                    => $this->pNomePai,
            'p_ocupacao_atual'              => $this->pOcupacaoAtual,
            'p_escolaridade'                => $this->pEscolaridade,
            'p_cor_raca'                    => $this->pCorRaca,
            'p_cor_raca_cod'                => $this->pCorRacaCod,
            'p_sexo'                        => $this->pSexo,
            'p_sexo_selecionado'            => $this->pSexoSelecionado,
            'p_estado_civil'                => $this->pEstadoCivil,
            'p_orientacao_sexual'           => $this->pOrientacaoSexual,
            'p_identidade_genero'           => $this->pIdentidadeGenero,
            'p_nome_social'                 => $this->pNomeSocial,
            'p_nacionalidade'               => $this->pNacionalidade,
            'p_pais_origem'                 => $this->pPaisOrigem,
            'p_naturalidade_uf'             => $this->pNaturalidadeUf ? mb_substr($this->pNaturalidadeUf, 0, 2) : null,
            'p_turista'                     => $this->pTurista,
            'p_situacao_rua'                => $this->pSituacaoRua,
            'p_end_cep'                     => $this->pEndCep,
            'p_end_pais'                    => $this->pEndPais,
            'p_end_estado_uf'               => $this->pEndEstadoUf    ? mb_substr($this->pEndEstadoUf, 0, 2)    : null,
            'p_end_municipio'               => $this->pEndMunicipio,
            'p_end_bairro'                  => $this->pEndBairro,
            'p_end_logradouro'              => $this->pEndLogradouro,
            'p_end_numero'                  => $this->pEndNumero,
            'p_end_complemento'             => $this->pEndComplemento,
            'p_end_km'                      => $this->pEndKm,
            'p_end_ibge'                    => $this->pEndIbge,
            'p_telefone_residencial'        => $this->pTelefoneResidencial,
            'p_telefone_comercial'          => $this->pTelefoneComercial,
            'p_email'                       => $this->pEmail,
            'p_motivo_ausencia_contato'     => $this->pMotivoAusenciaContato,
        ], fn ($v) => $v !== null && $v !== '');
    }
}
