<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AjudaHumanitariaSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        // 1. Criar Abrigos
        $abrigos = [
            [
                'nome' => 'Ginásio Municipal de Contagem',
                'tipo_local' => 'GINASIO',
                'endereco_completo' => 'Rua Santos Dumont, 450 - Centro',
                'municipio_id' => 1, // Ajustar conforme seu banco
                'bairro' => 'Centro',
                'cep' => '32010-010',
                'capacidade_maxima' => 150,
                'ocupacao_atual' => 87,
                'responsavel_nome' => 'Maria Silva Santos',
                'responsavel_telefone' => '(31) 98765-4321',
                'responsavel_cargo' => 'Coordenadora',
                'status' => 'ATIVO',
                'data_abertura' => Carbon::now()->subDays(15),
                'infraestrutura' => json_encode(['Banheiros', 'Cozinha', 'Enfermaria', 'Área de Lazer']),
                'recursos_disponiveis' => json_encode(['Colchões', 'Cobertores', 'Kit Higiene', 'Alimentação']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nome' => 'Escola Estadual Dom Pedro II',
                'tipo_local' => 'ESCOLA',
                'endereco_completo' => 'Av. Principal, 1200 - Eldorado',
                'municipio_id' => 1,
                'bairro' => 'Eldorado',
                'cep' => '32315-000',
                'capacidade_maxima' => 80,
                'ocupacao_atual' => 65,
                'responsavel_nome' => 'João Carlos Oliveira',
                'responsavel_telefone' => '(31) 99876-5432',
                'responsavel_cargo' => 'Diretor',
                'status' => 'ATIVO',
                'data_abertura' => Carbon::now()->subDays(12),
                'infraestrutura' => json_encode(['Banheiros', 'Cozinha', 'Salas de Aula']),
                'recursos_disponiveis' => json_encode(['Colchões', 'Alimentação']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'nome' => 'Igreja Matriz São Sebastião',
                'tipo_local' => 'IGREJA',
                'endereco_completo' => 'Praça da Matriz, s/n - Centro',
                'municipio_id' => 1,
                'bairro' => 'Centro',
                'cep' => '32000-000',
                'capacidade_maxima' => 50,
                'ocupacao_atual' => 50,
                'responsavel_nome' => 'Padre Antônio Ferreira',
                'responsavel_telefone' => '(31) 3333-4444',
                'responsavel_cargo' => 'Pároco',
                'status' => 'LOTADO',
                'data_abertura' => Carbon::now()->subDays(20),
                'infraestrutura' => json_encode(['Banheiros', 'Salão']),
                'recursos_disponiveis' => json_encode(['Colchões', 'Cobertores']),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($abrigos as $abrigo) {
            DB::table('abrigos')->insert($abrigo);
        }

        // 2. Criar Beneficiários
        $beneficiarios = [
            // DESABRIGADOS EM ABRIGO
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '123.456.789-01',
                'nome_responsavel' => 'Ana Paula Costa',
                'rg' => 'MG-12.345.678',
                'data_nascimento' => Carbon::parse('1985-03-15'),
                'telefone' => '(31) 98888-1111',
                'email' => 'ana.costa@email.com',
                'endereco_completo' => 'Rua das Flores, 123 - Bairro Industrial (área atingida)',
                'municipio_id' => 1,
                'bairro' => 'Industrial',
                'cep' => '32500-000',
                'numero_membros_familia' => 4,
                'situacao_vulnerabilidade' => 'DESABRIGADO',
                'data_cadastro' => Carbon::now()->subDays(15),
                'status' => 'ATIVO',
                'observacoes' => 'Casa completamente destruída pelas enchentes. Família com 2 crianças pequenas.',
                'abrigo_atual_id' => 1,
                'data_entrada_abrigo' => Carbon::now()->subDays(15),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '234.567.890-12',
                'nome_responsavel' => 'Carlos Eduardo Santos',
                'rg' => 'MG-23.456.789',
                'data_nascimento' => Carbon::parse('1978-07-22'),
                'telefone' => '(31) 99999-2222',
                'email' => null,
                'endereco_completo' => 'Rua Nova Esperança, 456 - Vila Nova',
                'municipio_id' => 1,
                'bairro' => 'Vila Nova',
                'cep' => '32600-100',
                'numero_membros_familia' => 5,
                'situacao_vulnerabilidade' => 'DESABRIGADO',
                'data_cadastro' => Carbon::now()->subDays(14),
                'status' => 'ATIVO',
                'observacoes' => 'Residência condenada pela defesa civil. Mãe idosa no grupo familiar.',
                'abrigo_atual_id' => 1,
                'data_entrada_abrigo' => Carbon::now()->subDays(14),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tipo_cadastro' => 'INDIVIDUAL',
                'cpf' => '345.678.901-23',
                'nome_responsavel' => 'Maria Conceição Silva',
                'rg' => 'MG-34.567.890',
                'data_nascimento' => Carbon::parse('1952-11-08'),
                'telefone' => '(31) 97777-3333',
                'email' => null,
                'endereco_completo' => 'Travessa do Comércio, 78 - Centro',
                'municipio_id' => 1,
                'bairro' => 'Centro',
                'cep' => '32000-050',
                'numero_membros_familia' => 1,
                'situacao_vulnerabilidade' => 'DESABRIGADO',
                'data_cadastro' => Carbon::now()->subDays(12),
                'status' => 'ATIVO',
                'observacoes' => 'Idosa vivendo sozinha. Casa destelhada e com risco de desabamento.',
                'abrigo_atual_id' => 2,
                'data_entrada_abrigo' => Carbon::now()->subDays(12),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '456.789.012-34',
                'nome_responsavel' => 'José Roberto Alves',
                'rg' => 'MG-45.678.901',
                'data_nascimento' => Carbon::parse('1990-05-30'),
                'telefone' => '(31) 96666-4444',
                'email' => 'jose.alves@email.com',
                'endereco_completo' => 'Rua Esperança, 234 - Periferia',
                'municipio_id' => 1,
                'bairro' => 'Periferia',
                'cep' => '32700-200',
                'numero_membros_familia' => 3,
                'situacao_vulnerabilidade' => 'DESABRIGADO',
                'data_cadastro' => Carbon::now()->subDays(20),
                'status' => 'ATIVO',
                'observacoes' => 'Perdeu todos os móveis e documentos na enchente.',
                'abrigo_atual_id' => 3,
                'data_entrada_abrigo' => Carbon::now()->subDays(20),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // DESALOJADOS (sem abrigo)
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '567.890.123-45',
                'nome_responsavel' => 'Sandra Regina Oliveira',
                'rg' => 'MG-56.789.012',
                'data_nascimento' => Carbon::parse('1982-09-14'),
                'telefone' => '(31) 95555-5555',
                'email' => 'sandra.oliveira@email.com',
                'endereco_completo' => 'Rua Sete de Setembro, 890 - Jardim América',
                'municipio_id' => 1,
                'bairro' => 'Jardim América',
                'cep' => '32800-300',
                'numero_membros_familia' => 3,
                'situacao_vulnerabilidade' => 'DESALOJADO',
                'data_cadastro' => Carbon::now()->subDays(10),
                'status' => 'ATIVO',
                'observacoes' => 'Família abrigada temporariamente na casa de parentes.',
                'abrigo_atual_id' => null,
                'data_entrada_abrigo' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '678.901.234-56',
                'nome_responsavel' => 'Paulo Henrique Ferreira',
                'rg' => 'MG-67.890.123',
                'data_nascimento' => Carbon::parse('1975-12-25'),
                'telefone' => '(31) 94444-6666',
                'email' => null,
                'endereco_completo' => 'Avenida Brasil, 1500 - São João',
                'municipio_id' => 1,
                'bairro' => 'São João',
                'cep' => '32900-400',
                'numero_membros_familia' => 6,
                'situacao_vulnerabilidade' => 'DESALOJADO',
                'data_cadastro' => Carbon::now()->subDays(8),
                'status' => 'ATIVO',
                'observacoes' => 'Casa alagada, aguardando liberação da defesa civil para retorno.',
                'abrigo_atual_id' => null,
                'data_entrada_abrigo' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // EM RISCO
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '789.012.345-67',
                'nome_responsavel' => 'Fernanda Cristina Souza',
                'rg' => 'MG-78.901.234',
                'data_nascimento' => Carbon::parse('1988-04-18'),
                'telefone' => '(31) 93333-7777',
                'email' => 'fernanda.souza@email.com',
                'endereco_completo' => 'Rua das Acácias, 321 - Morro Alto',
                'municipio_id' => 1,
                'bairro' => 'Morro Alto',
                'cep' => '33000-500',
                'numero_membros_familia' => 4,
                'situacao_vulnerabilidade' => 'EM_RISCO',
                'data_cadastro' => Carbon::now()->subDays(5),
                'status' => 'ATIVO',
                'observacoes' => 'Residência em área de risco de deslizamento. Monitoramento contínuo.',
                'abrigo_atual_id' => null,
                'data_entrada_abrigo' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'tipo_cadastro' => 'INDIVIDUAL',
                'cpf' => '890.123.456-78',
                'nome_responsavel' => 'Antônio Carlos Mendes',
                'rg' => 'MG-89.012.345',
                'data_nascimento' => Carbon::parse('1960-02-10'),
                'telefone' => '(31) 92222-8888',
                'email' => null,
                'endereco_completo' => 'Travessa da Paz, 12 - Encosta',
                'municipio_id' => 1,
                'bairro' => 'Encosta',
                'cep' => '33100-600',
                'numero_membros_familia' => 1,
                'situacao_vulnerabilidade' => 'EM_RISCO',
                'data_cadastro' => Carbon::now()->subDays(3),
                'status' => 'ATIVO',
                'observacoes' => 'Idoso morando sozinho em área de encosta. Necessita relocação urgente.',
                'abrigo_atual_id' => null,
                'data_entrada_abrigo' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // ISOLADO
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '901.234.567-89',
                'nome_responsavel' => 'Mariana Aparecida Lima',
                'rg' => 'MG-90.123.456',
                'data_nascimento' => Carbon::parse('1992-08-05'),
                'telefone' => '(31) 91111-9999',
                'email' => 'mariana.lima@email.com',
                'endereco_completo' => 'Estrada Rural, Km 5 - Zona Rural',
                'municipio_id' => 1,
                'bairro' => 'Zona Rural',
                'cep' => '33200-700',
                'numero_membros_familia' => 2,
                'situacao_vulnerabilidade' => 'ISOLADO',
                'data_cadastro' => Carbon::now()->subDays(7),
                'status' => 'ATIVO',
                'observacoes' => 'Isolada por queda de ponte. Acesso apenas por helicóptero.',
                'abrigo_atual_id' => null,
                'data_entrada_abrigo' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // INATIVO (já retornou para casa)
            [
                'tipo_cadastro' => 'FAMILIAR',
                'cpf' => '012.345.678-90',
                'nome_responsavel' => 'Ricardo Gonçalves',
                'rg' => 'MG-01.234.567',
                'data_nascimento' => Carbon::parse('1980-01-20'),
                'telefone' => '(31) 98000-0000',
                'email' => null,
                'endereco_completo' => 'Rua da Liberdade, 567 - Centro',
                'municipio_id' => 1,
                'bairro' => 'Centro',
                'cep' => '32000-100',
                'numero_membros_familia' => 2,
                'situacao_vulnerabilidade' => 'DESALOJADO',
                'data_cadastro' => Carbon::now()->subDays(30),
                'status' => 'INATIVO',
                'observacoes' => 'Retornou para casa após reformas. Situação estabilizada.',
                'abrigo_atual_id' => null,
                'data_entrada_abrigo' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($beneficiarios as $beneficiario) {
            DB::table('beneficiarios')->insert($beneficiario);
        }

        echo "✅ Seeder executado com sucesso!\n";
        echo "   - 3 abrigos criados\n";
        echo "   - 11 beneficiários criados\n";
        echo "   - 4 desabrigados em abrigo\n";
        echo "   - 2 desalojados\n";
        echo "   - 2 em risco\n";
        echo "   - 1 isolado\n";
        echo "   - 1 inativo\n";
    }
}
